export const SET_CUSTOMER_DESTINATION = 'SET_CUSTOMER_DESTINATION';
export const SET_CUSTOMER_ORIGIN = 'SET_CUSTOMER_ORIGIN';
export const SET_ROUTE_INFO = 'SET_ROUTE_INFO';

export const CUSTOMER_SEARCH_DRIVER = 'CUSTOMER_SEARCH_DRIVER';
export const CUSTOMER_SET_DRIVER_DATA = 'CUSTOMER_SET_DRIVER_DATA';
export const CUSTOMER_SET_DRIVER_ARRIVE = 'CUSTOMER_SET_DRIVER_ARRIVE';

export const TOGGLE_SELECT_VIA_MAP = 'TOGGLE_SELECT_VIA_MAP';
export const CUSTOMER_GET_ADDRESS_SUCCESS = 'CUSTOMER_GET_ADDRESS_SUCCESS';
export const CUSTOMER_GET_ADDRESS_START = 'CUSTOMER_GET_ADDRESS_START';

export const SET_USER_BOOK_STATE = 'SET_USER_BOOK_STATE';
