export const SET_CUSTOMER_DESTINATION = 'SET_CUSTOMER_DESTINATION';
export const SET_CUSTOMER_ORIGIN = 'SET_CUSTOMER_ORIGIN';
export const SET_ROUTE_INFO = 'SET_ROUTE_INFO';

export const CUSTOMER_SEARCH_DRIVER = 'CUSTOMER_SEARCH_DRIVER';

export const SET_USER_BOOK_STATE = 'SET_USER_BOOK_STATE';
